//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eefa.Inventory.Domain
{
    using Microsoft.EntityFrameworkCore.Metadata.Internal;
    using System;
    
    public class spErpDarkhastJoinDocumentHeadsParam

    {

        public DateTime? fromDate { get; set; }
        public DateTime? toDate { get; set; }
        public string RequestNo { get; set; }
       


    }
}
