//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eefa.Inventory.Domain
{
    using Microsoft.EntityFrameworkCore.Metadata.Internal;
    using System;
    public  class SpGetAuditByIdParam
    {
        public string TableName { get; set; }
        public Nullable<int> Id { get; set; }
       
        
    }
  
    public class spGetLogTableParam
    {
        public string ColumnName { get; set; }
        public string TableName { get; set; }
        public string ShemaName { get; set; }
        public Nullable<int> Id { get; set; }


    }
}
