//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eefa.Inventory.Domain
{
    using System;


    public  class spGetDocumentItemForTadbirParam
    {
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public int? CodeVoucherGroupId { get; set; }
        public int? DocumentNo { get; set; }
        public int? WarehouseId { get; set; }
        public int? UserId { get; set; }
        
    }
    public  class spReportControlsWarehouseLayoutQuantitiesByTadbirParam
    {
        public int warehouseId { get; set; }
        public int YearId { get; set; }



    }
    public class spDeleteInventory_StockFromTadbirParam
    {
        public int warehouseId { get; set; }
       
    }
    public  class spUpdateWarehouseCommodityAvailabe2Param
    {
      
        public int WarehouseId { get; set; }
        public int? YearId { get; set; }

        public int UserId { get; set; }
    }
    public  class spUpdateWarehouseCommodityAvailabe2
    {

        public int DocumentHeadId { get; set; }
        public int yearId { get; set; }

    }
    public class Stp_Acc_Foreign_ordersPram
    {
   
        public int CompanyId { get; set; }
        public int YearIds { get; set; }
        public int ReferenceId { get; set; }

    }
    public class Stp_Acc_Foreign_orders
    {

        public long? TotalDebit { get; set; }
        

    }
}
