 export interface ReceiptsExcelUploaded   {
  bankName: string;
  paymentNumber: string;
  amountPay: number;
  accountNo: string;
  creatorName: string;
  accountOwner: string;
  fullName: string;
  accountIsFloat: boolean;
  targetAccount: string;
  targetAccountCode: string;
  feeTypeTitle: string;
  paymentTitle: string;
  factorTitle: string;
  paymentStatusTitle: string;
  paymentCurrencyTitle: string;
  accountSheba: string;
  persianDateTime: string;
  code: string;
  createTime: string | null;
  stringAmount: string;
  stateTitle: string;
  bankCode: string;
  debtorSubsidiaryCode: string;
  debtorSubsidiaryName: string;
  customerType: number;
  creditorSubsidiaryCode: string;
  creditorSubsidiaryName: string;
  customerPaymentIdentifier: string;
  docNumber: string;
  accountCode: string;
  floatingCode: string;
  insertStatus: number;
  targetAccountName: string;
  receicePersianDate: string;
 }
