// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Purchase.Domain;




#nullable disable

namespace Eefa.Purchase.Infrastructure.Context.Configurations
{
    public partial class ReceiptItemsViewConfiguration : IEntityTypeConfiguration<ReceiptItemsView>
    {
        public void Configure(EntityTypeBuilder<ReceiptItemsView> entity)
        {
            entity.ToTable("ReceiptItemsView", "inventory");

            entity.HasComment("اسناد");

            entity.Property(e => e.Id).HasComment("شناسه");
            
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ReceiptItemsView> entity);
    }
}
