// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Purchase.Domain;



#nullable disable

namespace Eefa.Purchase.Infrastructure.Context.Configurations
{
    public partial class ViewCommodityConfiguration : IEntityTypeConfiguration<ViewCommodity>
    {
        public void Configure(EntityTypeBuilder<ViewCommodity> entity)
        {
            entity.ToTable("ViewCommodity", "inventory");

           // OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ViewCommodity> entity);
    }
}
