version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  headers:
    Access-Control-Allow-Origin: ["http://192.168.2.247:8080"]
    Access-Control-Allow-Methods: ["HEAD", "GET", "OPTIONS", "DELETE"]
    Access-Control-Allow-Credentials: ["true"]
    Access-Control-Allow-Headers: ["Authorization", "Accept", "Cache-Control"]