//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eefa.Inventory.Domain
{
    using Eefa.Common.Domain;
    using System;
    using System.Collections.Generic;
    
    public partial class CorrectionRequest : DomainBaseEntity
    {
       
        public int Status { get; set; }
        public int CodeVoucherGroupId { get; set; }
        public int? AccessPermissionId { get; set; } = default!;
        public int? YearId { get; set; } = default!;
        public Nullable<int> DocumentId { get; set; }
        public string OldData { get; set; }
        public int VerifierUserId { get; set; }
        public string PayLoad { get; set; }
        public string ApiUrl { get; set; }
        public string ViewUrl { get; set; }
        public string Description { get; set; }
        public string VerifierDescription { get; set; }
        public string RequesterDescription { get; set; }

    }
}
