//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eefa.Inventory.Domain
{
    using Eefa.Common.Domain;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "inventory.StockFromTadbir", Schema = "dbo")]
    public partial class inventory_StockFromTadbir : DomainBaseEntity
    {
        public string TadbirCode { get; set; }
        public string LocationName { get; set; }
        public string CommodityName { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> warehouseId { get; set; }
        public Nullable<int> WarehouseLayoutId { get; set; }
        
    }
}
