//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eefa.Common.Validation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations_fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations_fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eefa.Common.Validation.Resources.Validations_fa", typeof(Validations_fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید مجوز داشته باشید .
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید بیشتر از [1] وکمتر از [2] باشد.
        /// </summary>
        public static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت سند به تاریخ آینده امکان پذیر نیست .
        /// </summary>
        public static string CanNotCreateForFuture {
            get {
                return ResourceManager.GetString("CanNotCreateForFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت سند غیر موازنه  امکان پذیر نیست .
        /// </summary>
        public static string CanNotCreateUnbalancedVoucher {
            get {
                return ResourceManager.GetString("CanNotCreateUnbalancedVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سند.
        /// </summary>
        public static string CodeVoucherGroupId {
            get {
                return ResourceManager.GetString("CodeVoucherGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کالا.
        /// </summary>
        public static string CommodityId {
            get {
                return ResourceManager.GetString("CommodityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرفصل حساب بستانکار.
        /// </summary>
        public static string CreditAccountHeadId {
            get {
                return ResourceManager.GetString("CreditAccountHeadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه حساب بستانکار.
        /// </summary>
        public static string CreditAccountReferenceGroupId {
            get {
                return ResourceManager.GetString("CreditAccountReferenceGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب بستانکار.
        /// </summary>
        public static string CreditAccountReferenceId {
            get {
                return ResourceManager.GetString("CreditAccountReferenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرفصل  حساب بدهکار.
        /// </summary>
        public static string DebitAccountHeadId {
            get {
                return ResourceManager.GetString("DebitAccountHeadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه بدهکار.
        /// </summary>
        public static string DebitAccountReferenceGroupId {
            get {
                return ResourceManager.GetString("DebitAccountReferenceGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب بدهکار.
        /// </summary>
        public static string DebitAccountReferenceId {
            get {
                return ResourceManager.GetString("DebitAccountReferenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ سند.
        /// </summary>
        public static string DocumentDate {
            get {
                return ResourceManager.GetString("DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه سند.
        /// </summary>
        public static string DocumentHeadId {
            get {
                return ResourceManager.GetString("DocumentHeadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید بیشتر از [1] باشد.
        /// </summary>
        public static string Greater_than {
            get {
                return ResourceManager.GetString("Greater than", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه جدول خالی است.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سال جاری در حال استفاده میباشد.
        /// </summary>
        public static string InCurrentYearInUse {
            get {
                return ResourceManager.GetString("InCurrentYearInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این آیتم درحال استفاده است .
        /// </summary>
        public static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تستتتتتتتتتتت.
        /// </summary>
        public static string InvalidFromat {
            get {
                return ResourceManager.GetString("InvalidFromat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره صورتحساب.
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد سطح حساب صحیح نمیباشد.
        /// </summary>
        public static string IsNotValidCodeLevel {
            get {
                return ResourceManager.GetString("IsNotValidCodeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار  [1] قابل پذیرش نیست.
        /// </summary>
        public static string IsNotValidValue {
            get {
                return ResourceManager.GetString("IsNotValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود این مقدار الزامی است .
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار باید کمتر از [1] باشد.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا باید وارد سیستم شوید .
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل نامعتبر است.
        /// </summary>
        public static string MobileValidation {
            get {
                return ResourceManager.GetString("MobileValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این مقدار در دیتابیس وجود ندارد .
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی باید عدد باشد  .
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارقام کد با ارقام والد همخوانی ندارد .
        /// </summary>
        public static string ParentCodeNotValid {
            get {
                return ResourceManager.GetString("ParentCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید مجوز دسترسی داشته باشید .
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کالا.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از این داده در رابطه بین [1] و [2] استفاده شده است .
        /// </summary>
        public static string RelationBetween {
            get {
                return ResourceManager.GetString("RelationBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاراکتر ها باید [1] باشد.
        /// </summary>
        public static string SpecialLenght {
            get {
                return ResourceManager.GetString("SpecialLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این آیتم فقط میتواتند درست یا نادرست باشد .
        /// </summary>
        public static string TrueOrFalse {
            get {
                return ResourceManager.GetString("TrueOrFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نام قبلا استفاده شده است .
        /// </summary>
        public static string UniqueName {
            get {
                return ResourceManager.GetString("UniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت واحد.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به روز رسانی غیر ممکن است.
        /// </summary>
        public static string UpdateImpossible {
            get {
                return ResourceManager.GetString("UpdateImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ و شماره سند مطابقت ندارد .
        /// </summary>
        public static string VoucherAndDateCompatible {
            get {
                return ResourceManager.GetString("VoucherAndDateCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این گروه سند فعال نیست .
        /// </summary>
        public static string VoucherGroupNotActive {
            get {
                return ResourceManager.GetString("VoucherGroupNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت سند در روز تعطیل مجاز نیست .
        /// </summary>
        public static string VoucherInHolidayNotAllowed {
            get {
                return ResourceManager.GetString("VoucherInHolidayNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت سند در روز تعطیل مجاز نیست .
        /// </summary>
        public static string VoucherInHolidayNotAllowed1 {
            get {
                return ResourceManager.GetString("VoucherInHolidayNotAllowed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار.
        /// </summary>
        public static string WarehouseId {
            get {
                return ResourceManager.GetString("WarehouseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال مالی قابل دسترس نیست .
        /// </summary>
        public static string YearNotAccessible {
            get {
                return ResourceManager.GetString("YearNotAccessible", resourceCulture);
            }
        }
    }
}
