// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Purchase.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Purchase.Domain.Entities;

#nullable disable

namespace Eefa.Purchase.Infrastructure.Context.Configurations
{
    public partial class AccountReferencesRelReferencesGroupConfiguration : IEntityTypeConfiguration<AccountReferencesRelReferencesGroup>
    {
        public void Configure(EntityTypeBuilder<AccountReferencesRelReferencesGroup> entity)
        {
            entity.ToTable("AccountReferencesRelReferencesGroups", "accounting");

            

            
           // OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AccountReferencesRelReferencesGroup> entity);
    }
}
