// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Purchase.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Purchase.Domain.Entities;

#nullable disable

namespace Eefa.Purchase.Infrastructure.Context.Configurations
{
    public partial class AccountReferenceConfiguration : IEntityTypeConfiguration<AccountReference>
    {
        public void Configure(EntityTypeBuilder<AccountReference> entity)
        {
            entity.ToTable("AccountReferences", "accounting");

            

            
           // OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AccountReferencesGroup> entity);
    }
}
