// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Eefa.Purchase.Infrastructure.Context.Configurations
{
    public partial class AttachmentConfiguration : IEntityTypeConfiguration<Purchase.Domain.Attachment>
    {
        public void Configure(EntityTypeBuilder<Purchase.Domain.Attachment> entity)
        {
            entity.ToTable("Attachment", "Admin");
            entity.Property(e => e.Id).HasComment("شناسه");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Purchase.Domain.Attachment> entity);
    }
}
