// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Purchase.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Purchase.Domain.Entities;

#nullable disable

namespace Eefa.Purchase.Infrastructure.Context.Configurations
{
    public partial class BomValueHeaderConfiguration : IEntityTypeConfiguration<BomValueHeader>
    {
        public void Configure(EntityTypeBuilder<BomValueHeader> entity)
        {
            entity.ToTable("BomValueHeaders", "common");

            entity.HasComment("مواد فرمول ساخت");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.BomDate).HasComment("تاریخ فرمول ساخت");

            entity.Property(e => e.BomId).HasComment("کد فرمول ساخت");

            entity.Property(e => e.CommodityId).HasComment("کد کالا");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.HasOne(d => d.Bom)
                .WithMany(p => p.BomValueHeaders)
                .HasForeignKey(d => d.BomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValueHeader_BOM");

            entity.HasOne(d => d.Commodity)
                .WithMany(p => p.BomValueHeaders)
                .HasForeignKey(d => d.CommodityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValueHeader_Commodity");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BomValueHeader> entity);
    }
}
