// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Purchase.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Purchase.Domain.Entities;

#nullable disable

namespace Eefa.Purchase.Infrastructure.Context.Configurations
{
    public partial class BomValueConfiguration : IEntityTypeConfiguration<BomValue>
    {
        public void Configure(EntityTypeBuilder<BomValue> entity)
        {
            entity.ToTable("BomValues", "common");

            entity.HasComment("مقادیر فرمول ساخت");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.BomValueHeaderId).HasComment("کد سند فرمول ساخت");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.SubBomId).HasComment("کد فرمول ساخت زیر مجموعه");

            entity.Property(e => e.UsedCommodityId).HasComment("کد کالای مصرفی");

            entity.Property(e => e.Value).HasComment("مقدار");

            entity.HasOne(d => d.BomValueHeader)
                .WithMany(p => p.BomValues)
                .HasForeignKey(d => d.BomValueHeaderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValue_BomValueHeader");

            entity.HasOne(d => d.SubBom)
                .WithMany(p => p.BomValues)
                .HasForeignKey(d => d.SubBomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValue_BOM");

            entity.HasOne(d => d.UsedCommodity)
                .WithMany(p => p.BomValues)
                .HasForeignKey(d => d.UsedCommodityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValue_Commodity");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BomValue> entity);
    }
}
