// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Purchase.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Purchase.Domain.Entities;

#nullable disable

namespace Eefa.Purchase.Infrastructure.Context.Configurations
{
    public partial class CommodityConfiguration : IEntityTypeConfiguration<Commodity>
    {
        public void Configure(EntityTypeBuilder<Commodity> entity)
        {
            entity.ToTable("Commodities", "common");

            entity.HasComment("کالا ها");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.CommodityCategoryId).HasComment("کد گروه کالا");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.Descriptions)
                .HasMaxLength(1000)
                .HasComment("توضیحات");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.LevelCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("کد سطح");

            entity.Property(e => e.MaximumQuantity).HasComment("حداکثر تعداد");

            entity.Property(e => e.MeasureId).HasComment("کد واحد اندازه گیری");

            entity.Property(e => e.MinimumQuantity).HasComment("حداقل تعداد");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OrderQuantity).HasComment("تعداد سفارش");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.ParentId).HasComment("کد والد");

            entity.Property(e => e.PricingTypeBaseId).HasComment("نوع محاسبه قیمت");

            entity.Property(e => e.CompactCode)
                .HasMaxLength(50)
                .HasComment("کد محصول"); 
            
            entity.Property(e => e.TadbirCode)
                .HasMaxLength(50)
                .HasComment("کد محصول");    
            
            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .HasComment("کد محصول");

            entity.Property(e => e.Title)
                .HasMaxLength(500)
                .HasComment("عنوان");

            entity.Property(e => e.YearId).HasComment("کد سال");

            entity.HasOne(d => d.CommodityCategory)
                .WithMany(p => p.Commodities)
                .HasForeignKey(d => d.CommodityCategoryId)
                .HasConstraintName("FK_Commodity_CommodityCategory");

            entity.HasOne(d => d.Measure)
                .WithMany(p => p.Commodities)
                .HasForeignKey(d => d.MeasureId)
                .HasConstraintName("FK_Commodity_MeasureUnit");

            entity.HasOne(d => d.Parent)
                .WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_Commodity_Commodity");

            entity.HasOne(d => d.PricingTypeBase)
                .WithMany(p => p.Commodities)
                .HasForeignKey(d => d.PricingTypeBaseId)
                .HasConstraintName("FK_Commodity_BaseValues1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Commodity> entity);
    }
}
