// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Purchase.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Purchase.Domain.Entities;

#nullable disable

namespace Eefa.Purchase.Infrastructure.Context.Configurations
{
    public partial class DocumentNumberingFormatConfiguration : IEntityTypeConfiguration<DocumentNumberingFormat>
    {
        public void Configure(EntityTypeBuilder<DocumentNumberingFormat> entity)
        {
            entity.ToTable("DocumentNumberingFormats", "common");

            entity.HasComment("شماره گذاری اسناد");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.CodingTemplate)
                .IsRequired()
                .HasMaxLength(500)
                .HasComment("فرمت کد دهی");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.DocumentTypeBaseId).HasComment("کد نوع سند");

            entity.Property(e => e.IsActive).HasComment("فعال");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("عنوان");

            entity.HasOne(d => d.DocumentTypeBase)
                .WithMany(p => p.DocumentNumberingFormats)
                .HasForeignKey(d => d.DocumentTypeBaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DocumentNumberingFormat_BaseValues");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocumentNumberingFormat> entity);
    }
}
