// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Purchase.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Purchase.Domain.Entities;

#nullable disable

namespace Eefa.Purchase.Infrastructure.Context.Configurations
{
    public partial class StockConfiguration : IEntityTypeConfiguration<Stock>
    {
        public void Configure(EntityTypeBuilder<Stock> entity)
        {
            entity.ToTable("WarehouseStocks", "Purchase");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.CommodityId).HasComment("کد کالا");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

           

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.Quantity).HasComment("تعداد");

            entity.Property(e => e.ReservedQuantity).HasComment("موجودی منطقی");

            entity.Property(e => e.WarehousId).HasComment("کد انبار");

            entity.HasOne(d => d.Commodity)
                .WithMany(p => p.Stocks)
                .HasForeignKey(d => d.CommodityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Stoks_Commodity");

            entity.HasOne(d => d.Warehous)
                .WithMany(p => p.Stocks)
                .HasForeignKey(d => d.WarehousId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Stoks_Warehouses");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Stock> entity);
    }
}
