//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eefa.Inventory.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptGroupbyInvoiceView
    {
       

        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; } = default!;
        public int DocumentId { get; set; } = default!;
        public int CodeVoucherGroupId { get; set; } = default!;
        public string CodeVoucherGroupTitle { get; set; } = default!;
        public int CreditAccountReferenceId { get; set; } = default!;
        public string CreditReferenceTitle { get; set; } = default!;
        public string DocumentIds { get; set; } = default!;
        
        public Nullable<int> DebitAccountReferenceId { get; set; } = default!;
        public string DebitReferenceTitle { get; set; } = default!;
        public Nullable<int> CreditAccountHeadId { get; set; } = default!;
        public Nullable<int> VoucherHeadId { get; set; } = default!;

        public Nullable<int> CreditAccountReferenceGroupId { get; set; } = default!;
        public Nullable<int> DebitAccountHeadId { get; set; } = default!;
        public Nullable<int> DebitAccountReferenceGroupId { get; set; } = default!;
        public Nullable<int> DocumentStauseBaseValue { get; set; } = default!;
        public System.DateTime DocumentDate { get; set; } = default!;
        public int YearId { get; set; } = default!;
        public string InvoiceNo { get; set; } = default!;
        public Nullable<double> TotalItemPrice { get; set; } = default!;
        public Nullable<double> TotalProductionCost { get; set; } = default!;
        public Nullable<long> VatDutiesTax { get; set; } = default!;
        public Nullable<double> Quantity { get; set; } = default!;
        public Nullable<long> ExtraCost { get; set; } = default!;
        
        public bool IsImportPurchase { get; set; } = default!;
        public string Tags { get; set; } = default!;
        public string FinancialOperationNumber { get; set; }
        
        

    }
}
