// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Domain.Entities.Payables;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class Payables_DocumentsConfiguration : IEntityTypeConfiguration<Payables_Documents>
    {
        public void Configure(EntityTypeBuilder<Payables_Documents> entity)
        {
            entity.ToTable("Payables_Documents", "bursary");

            entity.HasIndex(e => e.ChequeBookSheetId, "IX_Payables_Documents_ChequeBookSheetId");

            entity.HasIndex(e => e.SubjectId, "IX_Payables_Documents_SubjectId");

            entity.HasIndex(e => e.BankAccountId, "IX_Payables_Documents_bankAccountId");

            entity.HasIndex(e => e.PayTypeId, "IX_Payables_Documents_payTypeId");

            entity.Property(e => e.Descp).HasMaxLength(500);


            entity.HasOne(d => d.BankAccount)
                .WithMany(p => p.Payables_Documents)
                .HasForeignKey(d => d.BankAccountId)
                .HasConstraintName("FK_Payables_Documents_AccountReferences");

            entity.HasOne(d => d.ChequeBookSheet)
                .WithMany(p => p.Payables_Documents)
                .HasForeignKey(d => d.ChequeBookSheetId)
                .HasConstraintName("FK_Payables_Documents_Payables_ChequeBooksSheets");

            entity.HasOne(d => d.CurrencyTypeBase)
                .WithMany(p => p.Payables_DocumentsCurrencyTypeBase)
                .HasForeignKey(d => d.CurrencyTypeBaseId)
                .HasConstraintName("FK_Payables_Documents_BaseValues1");

            entity.HasOne(d => d.PayType)
                .WithMany(p => p.Payables_DocumentsPayType)
                .HasForeignKey(d => d.PayTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payables_Documents_BaseValues2");

            entity.HasOne(d => d.Subject)
                .WithMany(p => p.Payables_DocumentsSubject)
                .HasForeignKey(d => d.SubjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payables_Documents_BaseValues");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Payables_Documents> entity);
    }
}
