// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class Payables_ChequeBooksSheetsConfiguration : IEntityTypeConfiguration<Payables_ChequeBooksSheets>
    {
        public void Configure(EntityTypeBuilder<Payables_ChequeBooksSheets> entity)
        {
            entity.ToTable("Payables_ChequeBooksSheets", "bursary");

            entity.HasIndex(e => new { e.ChequeBookId, e.ChequeSheetNo }, "IX_Payables_ChequeBooksSheets")
                .IsUnique();

            entity.Property(e => e.CancelDate).HasColumnType("datetime");

            entity.Property(e => e.CancelDescp).HasMaxLength(300);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.SayyadNo)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ChequeBook)
                .WithMany(p => p.Payables_ChequeBooksSheets)
                .HasForeignKey(d => d.ChequeBookId)
                .HasConstraintName("FK_Payables_ChequeBooksSheets_Payables_ChequeBooks");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Payables_ChequeBooksSheets> entity);
    }
}
