// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Domain.Entities.Payables;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class Payables_DocumentsOperationsConfiguration : IEntityTypeConfiguration<Payables_DocumentsOperations>
    {
        public void Configure(EntityTypeBuilder<Payables_DocumentsOperations> entity)
        {
            entity.ToTable("Payables_DocumentsOperations", "bursary");

            entity.HasIndex(e => e.DocumentId, "IX_Payables_DocumentsOperations_DocumentId");

            entity.HasIndex(e => e.OperationDate, "IX_Payables_DocumentsOperations_OperationDate");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.Descp).HasMaxLength(300);

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OperationDate).HasColumnType("datetime");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.HasOne(d => d.Document)
                .WithMany(p => p.Payables_DocumentsOperations)
                .HasForeignKey(d => d.DocumentId)
                .HasConstraintName("FK_Payables_DocumentsOperations_Payables_Documents");

            entity.HasOne(d => d.Operation)
                .WithMany(p => p.Payables_DocumentsOperations)
                .HasForeignKey(d => d.OperationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payables_DocumentsOperations_BaseValues");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Payables_DocumentsOperations> entity);
    }
}
