// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class Payables_ChequeBooksConfiguration : IEntityTypeConfiguration<Payables_ChequeBooks>
    {
        public void Configure(EntityTypeBuilder<Payables_ChequeBooks> entity)
        {
            entity.ToTable("Payables_ChequeBooks", "bursary");

            entity.HasIndex(e => e.BankAccountId, "IX_Payables_ChequeBooks_BankAccountId");

            entity.Property(e => e.BankAccountId).HasComment("حساب بانکی");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.GetDate)
                .HasColumnType("datetime")
                .HasComment("تاریخ دریافت");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.Serial)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("شماره سریال");

            entity.Property(e => e.SheetsCount).HasComment("تعداد برگه");

            entity.Property(e => e.StartNumber).HasComment("شروع از شماره");

            entity.HasOne(d => d.BankAccount)
                .WithMany(p => p.Payables_ChequeBooks)
                .HasForeignKey(d => d.BankAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payables_ChequeBooks_BankAccounts");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Payables_ChequeBooks> entity);
    }
}
