//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eefa.Inventory.Domain
{
    using System;
    
    public partial class spCommodityReportsSumAll
    {
        public Nullable<long> Prefix_Quantity { get; set; }
        public Nullable<long> Prefix_ItemUnitPrice { get; set; }
        public Nullable<long> Prefix_TotalItemPrice { get; set; }
        public Nullable<long> current_Enter_Quantity { get; set; }
        public Nullable<long> current_Enter_ItemUnitPrice { get; set; }
        public Nullable<long> current_Enter_TotalItemPrice { get; set; }
        public Nullable<long> current_Exit_Quantity { get; set; }
        public Nullable<long> current_Exit_ItemUnitPrice { get; set; }
        public Nullable<long> current_Exit_TotalItemPrice { get; set; }
        public Nullable<long> postfix_Quantity { get; set; }
        public Nullable<long> postfix_ItemUnitPrice { get; set; }
        public Nullable<long> postfix_TotalItemPrice { get; set; }
        
        

    }
}
