//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eefa.Inventory.Domain
{
    using System;
   
    public partial class spContradictionDebit
    {
        
        public Nullable<double> SumInventory { get; set; }
        public Nullable<double> SumAccounting { get; set; }
        public Nullable<double> Contradiction { get; set; }
        public Nullable<int> DocumentId { get; set; }
        
    }
}
