//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eefa.Inventory.Domain
{
    using System;
    
    public partial class spCommodityReports
    {
        public Nullable<double> Prefix_Quantity { get; set; }
        public Nullable<double> Prefix_ItemUnitPrice { get; set; }
        public Nullable<long> Prefix_TotalItemPrice { get; set; }
        public Nullable<double> current_Enter_Quantity { get; set; }
        public Nullable<double> current_Enter_ItemUnitPrice { get; set; }
        public Nullable<long> current_Enter_TotalItemPrice { get; set; }
        public Nullable<double> current_Exit_Quantity { get; set; }
        public Nullable<double> current_Exit_ItemUnitPrice { get; set; }
        public Nullable<long> current_Exit_TotalItemPrice { get; set; }
        public Nullable<double> postfix_Quantity { get; set; }
        public Nullable<double> postfix_ItemUnitPrice { get; set; }
        public Nullable<long> postfix_TotalItemPrice { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityTitle { get; set; }
        public string MeasureTitle { get; set; }
        public string CompactCode { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<long> RowsCount { get; set; }
        

    }
    public partial class spCommodityReportsRial
    {
        public Nullable<double> Prefix_Quantity { get; set; }
        
        public Nullable<long> Prefix_TotalItemPrice { get; set; }
        public Nullable<double> current_Enter_Quantity { get; set; }
      
        public Nullable<long> current_Enter_TotalItemPrice { get; set; }
        public Nullable<double> current_Exit_Quantity { get; set; }
        
        public Nullable<long> current_Exit_TotalItemPrice { get; set; }
        public Nullable<double> postfix_Quantity { get; set; }
        
        public Nullable<long> postfix_TotalItemPrice { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityTitle { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<long> RowsCount { get; set; }


    }
}
