//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eefa.Inventory.Domain
{
    using System;
    
    public partial class spCommodityReportsWithWarehouse
    {
        public Nullable<int> WarehouseId { get; set; }
        public string WarehouseTitle { get; set; }
        
        public Nullable<double> Prefix_TotalItemPrice { get; set; }
        public Nullable<double> current_Enter_Used_TotalItemPrice { get; set; }
        public Nullable<double> current_Enter_Purchase_TotalItemPrice { get; set; }
        public Nullable<double> current_Exit_TotalItemPrice { get; set; }
        public Nullable<double> postfix_TotalItemPrice { get; set; }


        public Nullable<double> Prefix_Quantity { get; set; }
        public Nullable<double> current_Enter_Used_Quantity { get; set; }
        public Nullable<double> current_Enter_Purchase_Quantity { get; set; }
        public Nullable<double> current_Exit_Quantity { get; set; }
        public Nullable<double> postfix_Quantity { get; set; }



    }
}
