//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eefa.Inventory.Domain
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Eefa.Common.Domain;


  
    public partial class spReceiptInvoice
    {
        public Nullable<int> CreditAccountReferenceId { get; set; }
        public string CreditReferenceTitle { get; set; }
        public string FinancialOperationNumber { get; set; }
        public string Description { get; set; }
        public string DocumentDescription { get { return string.Join("-", Description.Split('-').Distinct().ToArray()); }  }
        public Nullable<double> TotalItemPrice { get; set; }
        public Nullable<double> TotalProductionCost { get; set; }
        public Nullable<long> VatDutiesTax { get; set; }
       // public Nullable<int> DocumentId { get; set; }
        public Nullable<long> ExtraCost { get; set; }
        public Nullable<DateTime> InvoiceDate { get; set; }
        public Nullable<long> RowsCount { get; set; }

        public Nullable<int> VoucherNo { get; set; }
        public Nullable<int> VoucherHeadId { get; set; }

        
        


    }
}
