// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Admin.Data.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Admin.Data.Databases.Entities;

#nullable disable

namespace Eefa.Admin.Data.Databases.Configurations
{
    public partial class CorrectionRequestConfiguration : IEntityTypeConfiguration<CorrectionRequest>
    {
        public void Configure(EntityTypeBuilder<CorrectionRequest> entity)
        {
            entity.ToTable("CorrectionRequests", "common");

            entity.Property(e => e.ApiUrl)
                .IsRequired()
                .HasMaxLength(500);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.Description).HasMaxLength(500);

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OldData).IsRequired();

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.ViewUrl).HasMaxLength(500);

            entity.HasOne(d => d.CodeVoucherGroup)
               .WithMany(p => p.CorrectionRequests)
               .HasForeignKey(d => d.CodeVoucherGroupId)
               .OnDelete(DeleteBehavior.ClientSetNull)
               .HasConstraintName("FK_CorrectionRequests_CodeVoucherGroups");
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CorrectionRequest> entity);
    }
}
