// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Logistic.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Logistic.Domain;
#nullable disable

namespace Eefa.Logistic.Infrastructure.Context.Configurations
{
    public partial class PrehensionConfiguration : IEntityTypeConfiguration<Prehension>
    {
        public void Configure(EntityTypeBuilder<Prehension> entity)
        {
            entity.ToTable("EEFA-Prehension", "dbo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Prehension> entity);
    }
}
