// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class _CommoditiesCardexConfiguration : IEntityTypeConfiguration<_CommoditiesCardex>
    {
        public void Configure(EntityTypeBuilder<_CommoditiesCardex> entity)
        {
            entity.ToTable("_CommoditiesCardex", "common");

            entity.Property(e => e.Mode).HasComment(@"-1 خروجی
1 ورودی");

            entity.HasOne(d => d.CommodityldNavigation)
                .WithMany(p => p._CommoditiesCardex)
                .HasForeignKey(d => d.Commodityld)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CommoditiesCardex_Commodities");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<_CommoditiesCardex> entity);
    }
}
