// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;

#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class _FileAccessRoleUsersConfiguration : IEntityTypeConfiguration<_FileAccessRoleUsers>
    {
        public void Configure(EntityTypeBuilder<_FileAccessRoleUsers> entity)
        {
            entity.ToTable("_FileAccessRoleUsers", "bursary");

            entity.HasComment("کاربران دارای نقش دسترسی به فایل");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.DateTime).HasColumnType("datetime");

            entity.Property(e => e.Description).HasMaxLength(200);

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.HasOne(d => d.FileAccessRole)
                .WithMany(p => p._FileAccessRoleUsers)
                .HasForeignKey(d => d.FileAccessRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FileAccessRoleUsers_FileAccessRole");

            entity.HasOne(d => d.User)
                .WithMany(p => p._FileAccessRoleUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FileAccessRoleUsers_Users");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<_FileAccessRoleUsers> entity);
    }
}
