// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class ActivitiesConfiguration : IEntityTypeConfiguration<Activities>
    {
        public void Configure(EntityTypeBuilder<Activities> entity)
        {
            entity.ToTable("Activities", "bpms");

            entity.HasIndex(e => e.ProcessId);

            entity.HasIndex(e => e.ShapeId)
                .IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.FinishedRule)
                .HasMaxLength(50)
                .HasComment(@"Any=Finish the activity if any tasks of the activity finished,
 All=Finish the activity if all tasks of the activity finished");

            entity.Property(e => e.FormUrl).HasMaxLength(150);

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.Name).HasMaxLength(500);

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.StatusDescription).HasMaxLength(50);

            entity.HasOne(d => d.Process)
                .WithMany(p => p.Activities)
                .HasForeignKey(d => d.ProcessId)
                .HasConstraintName("FK_Activities_Processes");

            entity.HasOne(d => d.Shape)
                .WithOne(p => p.Activities)
                .HasForeignKey<Activities>(d => d.ShapeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Activity_Shapes");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Activities> entity);
    }
}
