// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class AutoVoucherFormulaConfiguration : IEntityTypeConfiguration<AutoVoucherFormula>
    {
        public void Configure(EntityTypeBuilder<AutoVoucherFormula> entity)
        {
            entity.ToTable("AutoVoucherFormula", "accounting");

            entity.HasComment("فرمول سند اتو ماتیک");

            entity.Property(e => e.AccountHeadId).HasComment("سرفصل حساب");

            entity.Property(e => e.Conditions)
                .HasMaxLength(300)
                .HasComment("شرط");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.DebitCreditStatus).HasComment("وضعیت مانده حساب debit 1 credit 2");

            entity.Property(e => e.Formula)
                .HasMaxLength(3000)
                .HasComment("ستونهای مقصد");

            entity.Property(e => e.GroupBy)
                .HasMaxLength(300)
                .HasComment("گروهبندی");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OrderIndex).HasComment("ترتیب آرتیکل سند ");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.RowDescription)
                .HasMaxLength(200)
                .HasComment("توضیحات سطر");

            entity.Property(e => e.SourceVoucherTypeId).HasComment("کد نوع سند");

            entity.Property(e => e.VoucherTypeId).HasComment("کد نوع سند");

            entity.HasOne(d => d.AccountHead)
                .WithMany(p => p.AutoVoucherFormulas)
                .HasForeignKey(d => d.AccountHeadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AutoVoucherFormula_AccountHead");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.AutoVoucherFormulas)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AutoVoucherFormula_Roles");

            entity.HasOne(d => d.VoucherType)
                .WithMany(p => p.AutoVoucherFormulas)
                .HasForeignKey(d => d.VoucherTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AutoVoucherFormula_CodeVoucherGroups");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AutoVoucherFormula> entity);
    }
}
