// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class AutoVoucherIncompleteVouchersConfiguration : IEntityTypeConfiguration<AutoVoucherIncompleteVouchers>
    {
        public void Configure(EntityTypeBuilder<AutoVoucherIncompleteVouchers> entity)
        {
            entity.ToTable("AutoVoucherIncompleteVouchers", "accounting");

            entity.HasComment("سندهای مکانیزه کامل نشده ");

            entity.Property(e => e.Id)
                .HasComment("شناسه")
                .ValueGeneratedOnAdd();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.Description)
                .HasMaxLength(300)
                .HasComment("توضیحات");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.RowId).HasComment("کد سطر");

            entity.Property(e => e.VoucherDate).HasComment("تاریخ سند");

            entity.Property(e => e.VoucherTypeId).HasComment("کد نوع سند");

            entity.HasOne(d => d.IdNavigation)
                .WithOne(p => p.AutoVoucherIncompleteVouchers)
                .HasForeignKey<AutoVoucherIncompleteVouchers>(d => d.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AutoVoucherIncompleteVouchers_CodeVoucherGroups");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.AutoVoucherIncompleteVouchers)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AutoVoucherIncompleteVouchers_Roles");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AutoVoucherIncompleteVouchers> entity);
    }
}
