// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class AutoVoucherRowsLinkConfiguration : IEntityTypeConfiguration<AutoVoucherRowsLink>
    {
        public void Configure(EntityTypeBuilder<AutoVoucherRowsLink> entity)
        {
            entity.ToTable("AutoVoucherRowsLink", "accounting");

            entity.HasComment("ارتباط آرتیکل سندهای مکانیزه ");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.AutoVoucherRowsLinks)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AutoVoucherRowsLink_Roles");

            entity.HasOne(d => d.VoucherType)
                .WithMany(p => p.AutoVoucherRowsLinks)
                .HasForeignKey(d => d.VoucherTypeId)
                .HasConstraintName("FK_AutoVoucherRowsLink_CodeVoucherGroups");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AutoVoucherRowsLink> entity);
    }
}
