// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class BankAccountCardexConfiguration : IEntityTypeConfiguration<BankAccountCardex>
    {
        public void Configure(EntityTypeBuilder<BankAccountCardex> entity)
        {
            entity.ToTable("BankAccountCardex", "bursary");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Amount).HasComment("حساب پشتیبان");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.InputMode)
                .HasDefaultValueSql("((1))")
                .HasComment(@"1 ورود پول
-1 خروج پول
");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.HasOne(d => d.BankAccount)
                .WithMany(p => p.BankAccountCardexes)
                .HasForeignKey(d => d.BankAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BankAccountCardex_BankAccounts");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.BankAccountCardexCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BankAccountCardex_Users");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.BankAccountCardexModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_BankAccountCardex_Users1");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.BankAccountCardexes)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BankAccountCardex_Roles");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BankAccountCardex> entity);
    }
}
