// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;

#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class BomItemsConfiguration : IEntityTypeConfiguration<BomItems>
    {
        public void Configure(EntityTypeBuilder<BomItems> entity)
        {
            entity.ToTable("BomItems", "common");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.HasOne(d => d.Bom)
                .WithMany(p => p.BomItems)
                .HasForeignKey(d => d.BomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomItem_Boms");

            entity.HasOne(d => d.Commodity)
                .WithMany(p => p.BomItems)
                .HasForeignKey(d => d.CommodityId)
                .HasConstraintName("FK_BomItems_Commodities");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.BomItemsCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomItem_Users");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.BomItemsModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_BomItem_Users1");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.BomItems)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomItem_Roles");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BomItems> entity);
    }
}
