// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class BomValuesConfiguration : IEntityTypeConfiguration<BomValues>
    {
        public void Configure(EntityTypeBuilder<BomValues> entity)
        {
            entity.ToTable("BomValues", "common");

            entity.HasComment("مقادیر فرمول ساخت");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.BomValueHeaderId).HasComment("کد سند فرمول ساخت");

            entity.Property(e => e.BomWarehouseId).HasDefaultValueSql("((30))");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.UsedCommodityId).HasComment("کد کالای مصرفی");

            entity.Property(e => e.Value).HasComment("مقدار");

            entity.HasOne(d => d.BomValueHeader)
                .WithMany(p => p.BomValues)
                .HasForeignKey(d => d.BomValueHeaderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValue_BomValueHeader");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.BomValuesCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValue_Users");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.BomValuesModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_BomValue_Users1");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.BomValues)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValue_Roles");

            entity.HasOne(d => d.UsedCommodity)
                .WithMany(p => p.BomValues)
                .HasForeignKey(d => d.UsedCommodityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValue_Commodity");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BomValues> entity);
    }
}
