// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class BomValueHeadersConfiguration : IEntityTypeConfiguration<BomValueHeaders>
    {
        public void Configure(EntityTypeBuilder<BomValueHeaders> entity)
        {
            entity.ToTable("BomValueHeaders", "common");

            entity.HasComment("مواد فرمول ساخت");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.BomDate).HasComment("تاریخ فرمول ساخت");

            entity.Property(e => e.BomId).HasComment("کد فرمول ساخت");

            entity.Property(e => e.CommodityId).HasComment("کد کالا");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.Name).HasMaxLength(100);

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.HasOne(d => d.Bom)
                .WithMany(p => p.BomValueHeaders)
                .HasForeignKey(d => d.BomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValueHeader_BOM");

            entity.HasOne(d => d.Commodity)
                .WithMany(p => p.BomValueHeaders)
                .HasForeignKey(d => d.CommodityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValueHeader_Commodity");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.BomValueHeadersCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValueHeader_Users");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.BomValueHeadersModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_BomValueHeader_Users1");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.BomValueHeaders)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValueHeader_Roles");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BomValueHeaders> entity);
    }
}
