// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class CodingTemplatePropertiesConfiguration : IEntityTypeConfiguration<CodingTemplateProperties>
    {
        public void Configure(EntityTypeBuilder<CodingTemplateProperties> entity)
        {
            entity.ToTable("CodingTemplateProperties", "common");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.IdNavigation)
                .WithOne(p => p.CodingTemplateProperties)
                .HasForeignKey<CodingTemplateProperties>(d => d.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CodingTemplateProperties_CodingTemplates");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CodingTemplateProperties> entity);
    }
}
