// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class CommodityMeasuresConfiguration : IEntityTypeConfiguration<CommodityMeasures>
    {
        public void Configure(EntityTypeBuilder<CommodityMeasures> entity)
        {
            entity.ToTable("CommodityMeasures", "common");

            entity.HasIndex(e => new { e.CommodityId, e.MeasureId })
                .HasName("IX_CommodityMeasures")
                .IsUnique();

            entity.HasOne(d => d.Commodity)
                .WithMany(p => p.CommodityMeasures)
                .HasForeignKey(d => d.CommodityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CommodityMeasures_Commodities");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.CommodityMeasures)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CommodityMeasures_Users");

            entity.HasOne(d => d.Measure)
                .WithMany(p => p.CommodityMeasures)
                .HasForeignKey(d => d.MeasureId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CommodityMeasures_MeasureUnits");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CommodityMeasures> entity);
    }
}
