// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class CommodityCategoriesConfiguration : IEntityTypeConfiguration<CommodityCategories>
    {
        public void Configure(EntityTypeBuilder<CommodityCategories> entity)
        {
            entity.ToTable("CommodityCategories", "common");

            entity.HasComment("گروه های کالا");

            entity.HasIndex(e => e.Code)
                .HasName("IX_CommodityCategories")
                .IsUnique();

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.CodingMode)
                .HasDefaultValueSql("((1))")
                .HasComment(@"1 کد سازی برا اساس گروه
2 کد سازی بر اساس مشخصات");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.IsReadOnly).HasComment("آیا فقط قابل خواندن است؟");

            entity.Property(e => e.LevelCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("کد سطح");

            entity.Property(e => e.MeasureId).HasComment("کدواحد اصلی کالا");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OrderIndex).HasComment("ترتیب نمایش");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.ParentId).HasComment("کد والد");

            entity.Property(e => e.RequireParentProduct).HasComment("this.Parent().Commodities");

            entity.Property(e => e.Title)
                .HasMaxLength(250)
                .HasComment("عنوان");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.CommodityCategoriesCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CommodityCategory_Users1");

            entity.HasOne(d => d.Measure)
                .WithMany(p => p.CommodityCategories)
                .HasForeignKey(d => d.MeasureId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CommodityCategory_MeasureUnit");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.CommodityCategoriesModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_CommodityCategory_Users");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.CommodityCategories)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CommodityCategory_Roles");

            entity.HasOne(d => d.Parent)
                .WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_CommodityCategory_CommodityCategory");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CommodityCategories> entity);
    }
}
