// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class CommodityCategoryPropertyItemsConfiguration : IEntityTypeConfiguration<CommodityCategoryPropertyItems>
    {
        public void Configure(EntityTypeBuilder<CommodityCategoryPropertyItems> entity)
        {
            entity.ToTable("CommodityCategoryPropertyItems", "common");

            entity.HasComment("آیتم های ویژگی گروه کالا");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.CategoryPropertyId).HasComment("کد ویژگی گروه");

            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .HasComment("کد");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsActive).HasComment("فعال است؟");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OrderIndex).HasComment("ترتیب نمایش");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.ParentId).HasComment("کد والد");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasComment("عنوان");

            entity.Property(e => e.UniqueName)
                .IsRequired()
                .HasComment("نام اختصاصی");

            entity.HasOne(d => d.CategoryProperty)
                .WithMany(p => p.CommodityCategoryPropertyItems)
                .HasForeignKey(d => d.CategoryPropertyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CommodityCategoryPropertyItems_CommodityCategoryProperties");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.CommodityCategoryPropertyItemsCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CommodityCategoryPropertyItems_Users");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.CommodityCategoryPropertyItemsModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_CommodityCategoryPropertyItems_Users1");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.CommodityCategoryPropertyItems)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CommodityCategoryPropertyItems_Roles");

            entity.HasOne(d => d.Parent)
                .WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_CommodityCategoryPropertyItems_CommodityCategoryPropertyItems");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CommodityCategoryPropertyItems> entity);
    }
}
