// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class CountryDivisionsConfiguration : IEntityTypeConfiguration<CountryDivisions>
    {
        public void Configure(EntityTypeBuilder<CountryDivisions> entity)
        {
            entity.ToTable("CountryDivisions", "common");

            entity.HasComment("شهر و استان");

            entity.Property(e => e.Id)
                .HasComment("شناسه")
                .ValueGeneratedNever();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById)
                .HasDefaultValueSql("((4))")
                .HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById)
                .HasDefaultValueSql("((4))")
                .HasComment("اصلاح کننده");

            entity.Property(e => e.Ostan)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment(" کد استان");

            entity.Property(e => e.OstanTitle)
                .HasMaxLength(255)
                .HasComment("نام استان");

            entity.Property(e => e.OwnerRoleId)
                .HasDefaultValueSql("((1))")
                .HasComment("نقش صاحب سند");

            entity.Property(e => e.Shahrestan)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("کد شهرستان");

            entity.Property(e => e.ShahrestanTitle)
                .HasMaxLength(255)
                .HasComment("نام شهرستان");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.CountryDivisionsCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CountryDivisions_Users1");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.CountryDivisionsModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_CountryDivisions_Users");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.CountryDivisions)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CountryDivisions_Roles");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CountryDivisions> entity);
    }
}
