// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class DataBaseMetadataConfiguration : IEntityTypeConfiguration<DataBaseMetadata>
    {
        public void Configure(EntityTypeBuilder<DataBaseMetadata> entity)
        {
            entity.ToTable("DataBaseMetadata", "common");

            entity.Property(e => e.Command)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.CommandProperty)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.Property)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.SchemaName).HasMaxLength(200);

            entity.Property(e => e.TableName).HasMaxLength(200);

            entity.Property(e => e.TableProperty)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.Translated).HasMaxLength(200);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DataBaseMetadata> entity);
    }
}
