// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class DataDictionaryConfiguration : IEntityTypeConfiguration<DataDictionary>
    {
        public void Configure(EntityTypeBuilder<DataDictionary> entity)
        {
            entity.ToTable("DataDictionary", "common");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.LaguageId).HasComment("کد زبان");

            entity.Property(e => e.ResourceName)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasComment("نام اصلی");

            entity.Property(e => e.ResourceValue)
                .HasMaxLength(250)
                .HasComment("مقدار اصلی");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DataDictionary> entity);
    }
}
