// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class DataDictionaryoldConfiguration : IEntityTypeConfiguration<DataDictionaryold>
    {
        public void Configure(EntityTypeBuilder<DataDictionaryold> entity)
        {
            entity.ToTable("DataDictionaryold", "common");

          

            entity.Property(e => e.CHARACTER_MAXIMUM_LENGTH).HasComment("حداکثر تعداد کاراکترها");

            entity.Property(e => e.COLUMN_DEFAULT)
                .HasMaxLength(4000)
                .HasComment("ستون پیش فرض");

            entity.Property(e => e.COLUMN_NAME)
                .HasMaxLength(128)
                .HasComment("نام ستون");

            entity.Property(e => e.DATA_TYPE)
                .HasMaxLength(128)
                .HasComment("نوع داده");

            entity.Property(e => e.DESCRIPTION)
                .HasMaxLength(50)
                .HasComment("توضیحات");

            entity.Property(e => e.IS_NULLABLE)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasComment("اجباری نیست");

            entity.Property(e => e.ORDINAL_POSITION).HasComment("موقعیت ترتیبی");

            entity.Property(e => e.TABLE_CATALOG)
                .HasMaxLength(128)
                .HasComment("فهرست جدول");

            entity.Property(e => e.TABLE_NAME)
                .IsRequired()
                .HasMaxLength(128)
                .HasComment("نام جدول");

            entity.Property(e => e.TABLE_SCHEMA)
                .HasMaxLength(128)
                .HasComment("شکل جدول");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DataDictionaryold> entity);
    }
}
