// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class FreightPaysConfiguration : IEntityTypeConfiguration<FreightPays>
    {
        public void Configure(EntityTypeBuilder<FreightPays> entity)
        {
            entity.ToTable("FreightPays", "bursary");

            entity.HasComment("پرداخت کرایه حمل بار");

            entity.Property(e => e.AccountSheba)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.BankFileDate).HasColumnType("datetime");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.DateTime).HasColumnType("date");

            entity.Property(e => e.FamilShebaAccounts).HasMaxLength(100);

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.NameShebaAccounts).HasMaxLength(100);

            entity.Property(e => e.OrderNumber).HasMaxLength(50);

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.PersianReceiptDate)
                .IsRequired()
                .HasMaxLength(25);

            entity.Property(e => e.PlateNo)
                .IsRequired()
                .HasMaxLength(22);

            entity.Property(e => e.ReceiptDate).HasColumnType("datetime");

            entity.Property(e => e.ReceiptNo)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.SSNAcountSheba).HasMaxLength(10);

            entity.Property(e => e.VehicleLoad)
                .IsRequired()
                .HasMaxLength(150);

            entity.Property(e => e.WaybillNumber).HasMaxLength(50);

            entity.HasOne(d => d.FreightPayList)
                .WithMany(p => p.FreightPays)
                .HasForeignKey(d => d.FreightPayListId)
                .HasConstraintName("FK_FreightPays_FreightPayList");

            entity.HasOne(d => d.Source)
                .WithMany(p => p.FreightPaysSources)
                .HasForeignKey(d => d.SourceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FreightPays_BaseValues");

            entity.HasOne(d => d.VehicleType)
                .WithMany(p => p.FreightPaysVehicleTypes)
                .HasForeignKey(d => d.VehicleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FreightPays_FreightPays1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FreightPays> entity);
    }
}
