// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class LanguagesConfiguration : IEntityTypeConfiguration<Languages>
    {
        public void Configure(EntityTypeBuilder<Languages> entity)
        {
            entity.ToTable("Languages", "admin");

            entity.HasComment("زبانها");

            entity.HasIndex(e => e.SeoCode)
                .HasName("IX_Languages")
                .IsUnique();

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.Culture)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("نماد");

            entity.Property(e => e.DefaultCurrencyBaseId).HasComment("واحد پول پیش فرض");

            entity.Property(e => e.DirectionBaseId).HasComment("راست چین");

            entity.Property(e => e.FlagImageUrl)
                .HasMaxLength(500)
                .HasComment("نماد پرچم کشور");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.SeoCode)
                .HasMaxLength(2)
                .HasComment("کد سئو");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("عنوان");

            entity.HasOne(d => d.DefaultCurrencyBase)
                .WithMany(p => p.LanguagesDefaultCurrencyBases)
                .HasForeignKey(d => d.DefaultCurrencyBaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Languages_BaseValues1");

            entity.HasOne(d => d.DirectionBase)
                .WithMany(p => p.LanguagesDirectionBases)
                .HasForeignKey(d => d.DirectionBaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Languages_BaseValues");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Languages> entity);
    }
}
