// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class MoadianInvoiceHeadersConfiguration : IEntityTypeConfiguration<MoadianInvoiceHeaders>
    {
        public void Configure(EntityTypeBuilder<MoadianInvoiceHeaders> entity)
        {
            entity.ToTable("MoadianInvoiceHeaders", "accounting");

            entity.Property(e => e.ACC)
                .HasMaxLength(50)
                .HasComment("کد تفضیل شناور");

            entity.Property(e => e.Bbc).HasMaxLength(50);

            entity.Property(e => e.Bid).HasMaxLength(50);

            entity.Property(e => e.Billid).HasMaxLength(50);

            entity.Property(e => e.Bpc).HasMaxLength(50);

            entity.Property(e => e.Bpn).HasMaxLength(50);

            entity.Property(e => e.CCC)
                .HasMaxLength(50)
                .HasComment("کد مشتری");

            entity.Property(e => e.CNN)
                .HasMaxLength(50)
                .HasComment("نام مشتری");

            entity.Property(e => e.Cap).HasColumnType("money");

            entity.Property(e => e.Cdcn).HasMaxLength(50);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.Crn).HasMaxLength(50);

            entity.Property(e => e.Inno)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Insp).HasColumnType("money");

            entity.Property(e => e.Irtaxid).HasMaxLength(50);

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.IsSandbox)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.ReferenceId).HasMaxLength(100);

            entity.Property(e => e.Sbc).HasMaxLength(50);

            entity.Property(e => e.Scc).HasMaxLength(50);

            entity.Property(e => e.Scln).HasMaxLength(50);

            entity.Property(e => e.Status).HasMaxLength(50);

            entity.Property(e => e.Tadis).HasColumnType("money");

            entity.Property(e => e.Tax17).HasColumnType("money");

            entity.Property(e => e.TaxId).HasMaxLength(50);

            entity.Property(e => e.Tbill).HasColumnType("money");

            entity.Property(e => e.Tdis).HasColumnType("money");

            entity.Property(e => e.Tinb).HasMaxLength(50);

            entity.Property(e => e.Tins)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Tocv).HasColumnType("money");

            entity.Property(e => e.Todam).HasColumnType("money");

            entity.Property(e => e.Tonw).HasColumnType("money");

            entity.Property(e => e.Torv).HasColumnType("money");

            entity.Property(e => e.Tprdis).HasColumnType("money");

            entity.Property(e => e.Tvam).HasColumnType("money");

            entity.Property(e => e.Tvop).HasColumnType("money");

            entity.Property(e => e.UId).HasMaxLength(100);

            entity.HasOne(d => d.AccountReference)
                .WithMany(p => p.MoadianInvoiceHeaders)
                .HasForeignKey(d => d.AccountReferenceId)
                .HasConstraintName("FK_MoadianInvoiceHeaders_AccountReferences");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.MoadianInvoiceHeaders)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MoadianInvoiceHeaders_Users");

            entity.HasOne(d => d.Person)
                .WithMany(p => p.MoadianInvoiceHeaders)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_MoadianInvoiceHeaders_Persons");

            entity.HasOne(d => d.VerificationCode)
                .WithMany(p => p.MoadianInvoiceHeaders)
                .HasForeignKey(d => d.VerificationCodeId)
                .HasConstraintName("FK_MoadianInvoiceHeaders_VerificationCodes");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MoadianInvoiceHeaders> entity);
    }
}
