// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class PersonFingerprintConfiguration : IEntityTypeConfiguration<PersonFingerprint>
    {
        public void Configure(EntityTypeBuilder<PersonFingerprint> entity)
        {
            entity.ToTable("PersonFingerprint", "admin");

            entity.HasComment("اثر انگشت");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.FingerBaseId).HasComment("شماره انگشت");

            entity.Property(e => e.FingerPrintPhotoURL)
                .HasMaxLength(1000)
                .HasComment("عکس اثر انگشت");

            entity.Property(e => e.FingerPrintTemplate)
                .IsRequired()
                .HasMaxLength(2000)
                .IsUnicode(false)
                .HasComment("الگوی اثر انگشت");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.PersonId).HasComment("کد شخص");

            entity.HasOne(d => d.FingerBase)
                .WithMany(p => p.PersonFingerprints)
                .HasForeignKey(d => d.FingerBaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonFingerprint_BaseValues");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonFingerprint> entity);
    }
}
