// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class PersonRelAttachmentsConfiguration : IEntityTypeConfiguration<PersonRelAttachments>
    {
        public void Configure(EntityTypeBuilder<PersonRelAttachments> entity)
        {
            entity.ToTable("PersonRelAttachments", "admin");

            entity.HasComment("پیوست های اشخاص");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.AttachmentId).HasComment("ضمائم");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.PersonId).HasComment("کد شخص");

            entity.HasOne(d => d.Attachment)
                .WithMany(p => p.PersonRelAttachments)
                .HasForeignKey(d => d.AttachmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonRelAttachments_Attachment");

            entity.HasOne(d => d.CreatedBy)
                .WithMany(p => p.PersonRelAttachmentsCreatedBies)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonRelAttachments_Users1");

            entity.HasOne(d => d.ModifiedBy)
                .WithMany(p => p.PersonRelAttachmentsModifiedBies)
                .HasForeignKey(d => d.ModifiedById)
                .HasConstraintName("FK_PersonRelAttachments_Users");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.PersonRelAttachments)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonRelAttachments_Roles");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonRelAttachments> entity);
    }
}
