// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class ProcessesConfiguration : IEntityTypeConfiguration<Processes>
    {
        public void Configure(EntityTypeBuilder<Processes> entity)
        {
            entity.ToTable("Processes", "bpms");

            entity.HasIndex(e => e.ShapeId)
                .IsUnique()
                .HasFilter("([ShapeId] IS NOT NULL)");

            entity.HasIndex(e => e.WorkflowId);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.HasOne(d => d.Shape)
                .WithOne(p => p.Processes)
                .HasForeignKey<Processes>(d => d.ShapeId)
                .HasConstraintName("FK_Process_Shapes");

            entity.HasOne(d => d.Workflow)
                .WithMany(p => p.Processes)
                .HasForeignKey(d => d.WorkflowId)
                .HasConstraintName("FK_Processes_Workflows");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Processes> entity);
    }
}
