// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class RequestsConfiguration : IEntityTypeConfiguration<Requests>
    {
        public void Configure(EntityTypeBuilder<Requests> entity)
        {
            entity.ToTable("Requests", "bpms");

            entity.HasIndex(e => e.Id)
                .IsUnique();

            entity.Property(e => e.ApplicantComment).HasMaxLength(500);

            entity.Property(e => e.ExtraPayload)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.JsonData).HasMaxLength(4000);

            entity.Property(e => e.QueueToSubscribe)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.ResponderComment).HasMaxLength(500);

            entity.Property(e => e.Url)
                .HasMaxLength(500)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Requests> entity);
    }
}
