// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class RunningWorkflowConfiguration : IEntityTypeConfiguration<RunningWorkflow>
    {
        public void Configure(EntityTypeBuilder<RunningWorkflow> entity)
        {
            entity.ToTable("RunningWorkflow", "bpms");

            entity.HasComment("جریان های کاری فعال");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.CreatorId).HasComment("شناسه ی شخص یا نقش ایجاد کننده ی فعالیت بعدی");

            entity.Property(e => e.EndDate)
                .HasColumnType("datetime")
                .HasComment("تاریخ و زمان پایان");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.StartDate)
                .HasColumnType("datetime")
                .HasComment("تاریخ و زمان شروع");

            entity.Property(e => e.WorkflowId).HasComment("کد جریان کاری");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RunningWorkflow> entity);
    }
}
