// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class RuntimeProcessConfiguration : IEntityTypeConfiguration<RuntimeProcess>
    {
        public void Configure(EntityTypeBuilder<RuntimeProcess> entity)
        {
            entity.ToTable("RuntimeProcess", "bpms");

            entity.HasIndex(e => e.RuntimeWorkflowId);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.EndDate).HasColumnType("datetime");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.StartDate).HasColumnType("datetime");

            entity.HasOne(d => d.RuntimeWorkflow)
                .WithMany(p => p.RuntimeProcesses)
                .HasForeignKey(d => d.RuntimeWorkflowId)
                .HasConstraintName("FK_RuntimeProcess_RuntimeWorkflow");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RuntimeProcess> entity);
    }
}
