// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class ServiceActivitiesConfiguration : IEntityTypeConfiguration<ServiceActivities>
    {
        public void Configure(EntityTypeBuilder<ServiceActivities> entity)
        {
            entity.ToTable("ServiceActivities", "bpms");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.Parameters)
                .IsRequired()
                .HasMaxLength(400);

            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasOne(d => d.IdNavigation)
                .WithOne(p => p.ServiceActivities)
                .HasForeignKey<ServiceActivities>(d => d.Id)
                .HasConstraintName("FK_ServiceActivities_Activities");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ServiceActivities> entity);
    }
}
