// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class ValidationMessagesConfiguration : IEntityTypeConfiguration<ValidationMessages>
    {
        public void Configure(EntityTypeBuilder<ValidationMessages> entity)
        {
            entity.ToTable("ValidationMessages", "admin");

            entity.HasComment("پیام های اعتبار سنجی");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.IsDeleted)
                .HasDefaultValueSql("((0))")
                .HasComment("آیا حذف شده است؟");

            entity.Property(e => e.Keyword)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("کلمات کلیدی");

            entity.Property(e => e.LanguageId).HasComment("کد زبان");

            entity.Property(e => e.Message)
                .IsRequired()
                .HasMaxLength(250)
                .HasComment("پیام");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.HasOne(d => d.Language)
                .WithMany(p => p.ValidationMessages)
                .HasForeignKey(d => d.LanguageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ValidationMessages_Language");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.ValidationMessages)
                .HasForeignKey(d => d.OwnerRoleId)
                .HasConstraintName("FK_ValidationMessages_Roles");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ValidationMessages> entity);
    }
}
