// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Bursary.Infrastructure.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Bursary.Domain.Entities;
#nullable disable

namespace Eefa.Bursary.Infrastructure.EntityConfigurations.Configurations
{
    public partial class VouchersDetailConfiguration : IEntityTypeConfiguration<VouchersDetail>
    {
        public void Configure(EntityTypeBuilder<VouchersDetail> entity)
        {
            entity.HasKey(e => e.Id)
                .IsClustered(false);

            entity.ToTable("VouchersDetail", "accounting");

            entity.HasComment("آرتیکل های سند حسابداری");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.AccountHeadId).HasComment("سرفصل حساب ");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.Credit).HasComment("اعتبار");

            entity.Property(e => e.CurrencyAmount).HasComment("مبلغ ارز");

            entity.Property(e => e.CurrencyFee).HasComment("نرخ ارزبه ریال");

            entity.Property(e => e.CurrencyTypeBaseId).HasComment("نوع ارز");

            entity.Property(e => e.Debit).HasComment("بدهکار");

            entity.Property(e => e.DebitCreditStatus)
                .HasComment("وضعیت مانده حساب")
                .HasComputedColumnSql("(CONVERT([tinyint],case when isnull([debit],(0))>(0) then (1) else (2) end))");

            entity.Property(e => e.DocumentId).HasComment("شماره سند مرتبط ");

            entity.Property(e => e.DocumentIds)
                .HasMaxLength(1000)
                .HasComment("لیست اسناد مرتبط");

            entity.Property(e => e.DocumentNo)
                .HasMaxLength(50)
                .HasComment("شماره سند مرتبط ");

            entity.Property(e => e.FinancialOperationNumber)
                .HasMaxLength(50)
                .HasComment("شماره فرم عملیات مالی");

            entity.Property(e => e.InvoiceNo)
                .HasMaxLength(50)
                .HasComment("شماره فاکتور مشتری");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.Level1).HasComment("سطح 1");

            entity.Property(e => e.Level2).HasComment("سطح 2");

            entity.Property(e => e.Level3).HasComment("سطح 3");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.Quantity).HasComment("مقدار ویژگی تعداد ");

            entity.Property(e => e.ReferenceDate).HasComment("تاریخ مرجع");

            entity.Property(e => e.ReferenceId1).HasComment("کد مرجع1");

            entity.Property(e => e.ReferenceId2).HasComment("کد مرجع2");

            entity.Property(e => e.ReferenceId3).HasComment("کد مرجع3");

            entity.Property(e => e.Remain)
                .HasComment("باقیمانده")
                .HasComputedColumnSql("(isnull([Debit],(0))-isnull([Credit],(0)))");

            entity.Property(e => e.RequestNo)
                .HasMaxLength(50)
                .HasComment("شماره درخواست ");

            entity.Property(e => e.RowIndex).HasComment("ترتیب سطر");

            entity.Property(e => e.Tag)
                .HasMaxLength(500)
                .HasComment("تگ");

            entity.Property(e => e.TraceNumber).HasComment("ویژگی پیگیری دارد  ");

            entity.Property(e => e.VoucherDate).HasComment("تاریخ سند");

            entity.Property(e => e.VoucherId).HasComment("کد سند");

            entity.Property(e => e.VoucherRowDescription)
                .IsRequired()
                .HasMaxLength(3000)
                .HasComment("شرح آرتیکل  سند");

            entity.Property(e => e.Weight).HasComment("مقدار مرجع");

            entity.HasOne(d => d.AccountHead)
                .WithMany(p => p.VouchersDetails)
                .HasForeignKey(d => d.AccountHeadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VouchersDetail_AccountHead");

            entity.HasOne(d => d.AccountReferencesGroup)
                .WithMany(p => p.VouchersDetails)
                .HasForeignKey(d => d.AccountReferencesGroupId)
                .HasConstraintName("FK_VouchersDetail_AccountReferencesGroups");

            entity.HasOne(d => d.CurrencyTypeBase)
                .WithMany(p => p.VouchersDetails)
                .HasForeignKey(d => d.CurrencyTypeBaseId)
                .HasConstraintName("FK_VouchersDetail_BaseValues");

            entity.HasOne(d => d.OwnerRole)
                .WithMany(p => p.VouchersDetails)
                .HasForeignKey(d => d.OwnerRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VouchersDetail_Roles");

            entity.HasOne(d => d.ReferenceId1Navigation)
                .WithMany(p => p.VouchersDetailReferenceId1Navigation)
                .HasForeignKey(d => d.ReferenceId1)
                .HasConstraintName("FK_VouchersDetail_References");

            entity.HasOne(d => d.ReferenceId2Navigation)
                .WithMany(p => p.VouchersDetailReferenceId2Navigation)
                .HasForeignKey(d => d.ReferenceId2)
                .HasConstraintName("FK_VouchersDetail_References1");

            entity.HasOne(d => d.ReferenceId3Navigation)
                .WithMany(p => p.VouchersDetailReferenceId3Navigation)
                .HasForeignKey(d => d.ReferenceId3)
                .HasConstraintName("FK_VouchersDetail_References2");

            entity.HasOne(d => d.Voucher)
                .WithMany(p => p.VouchersDetails)
                .HasForeignKey(d => d.VoucherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VouchersDetail_VouchersHead");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VouchersDetail> entity);
    }
}
