// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Sale.Domain.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Sale.Domain.Aggregates.CustomerAggregate;

#nullable disable

namespace Eefa.Sale.Domain.reverse.Configurations
{
    public partial class PersonsConfiguration : IEntityTypeConfiguration<Person>
    {
        public void Configure(EntityTypeBuilder<Person> entity)
        {
            entity.ToTable("Persons", "admin");

            entity.HasComment("اشخاص");

            entity.HasIndex(e => e.NationalNumber)
                .HasName("IX_Persons")
                .IsUnique();

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.AccountReferenceId).HasComment("کد طرف حساب");

            entity.Property(e => e.BirthDate).HasComment("تاریخ تولد");

            entity.Property(e => e.BirthPlaceCountryDivisionId).HasComment("شهر محل تولد");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.Email)
                .HasMaxLength(320)
                .IsUnicode(false)
                .HasComment("ایمیل");

            entity.Property(e => e.FatherName)
                .HasMaxLength(100)
                .HasComment("نام پدر");

            entity.Property(e => e.FirstName)
                .IsRequired(false)
                .HasMaxLength(100)
                .HasComment("نام");

            entity.Property(e => e.GenderBaseId).HasComment("جنسیت");

            entity.Property(e => e.GovernmentalBaseId).HasComment("دولتی/ غیر دولتی");

            entity.Property(e => e.IdentityNumber)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("شماره شناسنامه");

            entity.Property(e => e.InsuranceNumber)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("شماره بیمه");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("نام خانوادگی");

            entity.Property(e => e.LegalBaseId).HasComment("حقیقی/ حقوقی");

            entity.Property(e => e.MobileJson)
                .HasMaxLength(1000)
                .HasComment("شماره موبایل");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.NationalNumber)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("کد ملی");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.PhotoURL)
                .HasMaxLength(1000)
                .HasComment("لینک عکس شخص");

            entity.Property(e => e.SignatureURL)
                .HasMaxLength(1000)
                .HasComment("لینک امضا");

            entity.HasOne(d => d.AccountReference)
                .WithMany(p => p.Persons)
                .HasForeignKey(d => d.AccountReferenceId)
                .HasConstraintName("FK_Persons_AccountReferences");

            entity.HasOne(d => d.GenderBase)
                .WithMany(p => p.PersonsGenderBases)
                .HasForeignKey(d => d.GenderBaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Persons_BaseValues");

            entity.HasOne(d => d.GovernmentalBase)
                .WithMany(p => p.PersonsGovernmentalBases)
                .HasForeignKey(d => d.GovernmentalBaseId)
                .HasConstraintName("FK_Persons_BaseValues1");

            entity.HasOne(d => d.LegalBase)
                .WithMany(p => p.PersonsLegalBases)
                .HasForeignKey(d => d.LegalBaseId)
                .HasConstraintName("FK_Persons_BaseValues2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Person> entity);
    }
}
