// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Sale.Domain.reverse;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Sale.Domain.Aggregates;

#nullable disable

namespace Eefa.Sale.Domain.reverse.Configurations
{
    public partial class SalesAgentsConfiguration : IEntityTypeConfiguration<SalesAgents>
    {
        public void Configure(EntityTypeBuilder<SalesAgents> entity)
        {
            entity.ToTable("SalesAgents", "Sale");

            entity.Property(e => e.Id).HasComment("شماره ");

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("کد ");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasComment("شرح ");

            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("((1))")
                .HasComment("فعال");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.PersonId).HasComment("کد شخص ");

            entity.HasOne(d => d.Person)
                .WithMany(p => p.SalesAgents)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesAgents_Persons");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SalesAgents> entity);
    }
}
