// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Commodity.Data.Context;
using Eefa.Commodity.Data.Entities;
using Eefa.Common;
using Eefa.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Eefa.Commodity.Data.Context.Configurations
{
    public partial class BaseValueTypeConfiguration : IEntityTypeConfiguration<BaseValueType>
    {
        public void Configure(EntityTypeBuilder<BaseValueType> entity)
        {
            entity.ToTable("BaseValueTypes", "admin", tb =>
                {
                    tb.HasComment("نوع اطلاعات پایه ");
                    tb.HasTrigger("BaseValueTypesInsertTrriger");
                });

            entity.HasIndex(e => e.LevelCode, "IX_BaseValueTypes").IsUnique();

            entity.HasIndex(e => e.UniqueName, "IX_BaseValueTypes_1").IsUnique();

            entity.Property(e => e.Id).HasComment("شناسه");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");
            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");
            entity.Property(e => e.GroupName)
                .HasMaxLength(50)
                .HasComment("نام گروه");
            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");
            entity.Property(e => e.IsReadOnly).HasComment("آیا فقط قابل خواندن است؟");
            entity.Property(e => e.LevelCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("((0))")
                .HasComment("کد سطح");
            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");
            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");
            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");
            entity.Property(e => e.ParentId).HasComment("کد والد");
            entity.Property(e => e.SubSystem)
                .HasMaxLength(50)
                .HasComment("زیر سیستم");
            entity.Property(e => e.Title)
                .HasMaxLength(250)
                .HasComment("عنوان");
            entity.Property(e => e.UniqueName)
                .HasMaxLength(50)
                .HasComment("نام اختصاصی");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_BaseValueTypes_BaseValueTypes1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BaseValueType> entity);
    }
}
