// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Commodity.Data.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Commodity.Data.Entities;

#nullable disable

namespace Eefa.Commodity.Data.Context.Configurations
{
    public partial class BomConfiguration : IEntityTypeConfiguration<Bom>
    {
        public void Configure(EntityTypeBuilder<Bom> entity)
        {
            entity.ToTable("Boms", "common");

            entity.HasComment("فرمول های ساخت");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.CommodityCategoryId).HasComment("کد گروه کالا");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(400);

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.LevelCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("کد سطح");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");


            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.CommodityCategory)
                .WithMany(p => p.Boms)
                .HasForeignKey(d => d.CommodityCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BOM_CommodityCategory");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Bom> entity);
    }
}
