// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Commodity.Data.Context;
using Eefa.Commodity.Data.Entities;
using Eefa.Common;
using Eefa.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Eefa.Commodity.Data.Context.Configurations
{
    public partial class BomValueHeaderConfiguration : IEntityTypeConfiguration<BomValueHeader>
    {
        public void Configure(EntityTypeBuilder<BomValueHeader> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_BomValueHeader");

            entity.ToTable("BomValueHeaders", "common", tb => tb.HasComment("مواد فرمول ساخت"));

            entity.Property(e => e.Id).HasComment("شناسه");
            entity.Property(e => e.BomDate).HasComment("تاریخ فرمول ساخت");
            entity.Property(e => e.BomId).HasComment("کد فرمول ساخت");
            entity.Property(e => e.CommodityId).HasComment("کد کالا");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");
            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");
            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");
            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");
            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.HasOne(d => d.Bom).WithMany(p => p.BomValueHeaders)
                .HasForeignKey(d => d.BomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BomValueHeader_BOM");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BomValueHeader> entity);
    }
}
