// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Commodity.Data.Context;
using Eefa.Commodity.Data.Entities;
using Eefa.Common;
using Eefa.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Eefa.Commodity.Data.Context.Configurations
{
    public partial class CommoditeisViewConfiguration : IEntityTypeConfiguration<CommoditeisView>
    {
        public void Configure(EntityTypeBuilder<CommoditeisView> entity)
        {
            entity
                .HasNoKey()
                .ToView("CommoditeisView", "common");

            entity.Property(e => e.CategoryLevelCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CategoryTitle).HasMaxLength(250);
            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CommodityNationalId).HasMaxLength(50);
            entity.Property(e => e.CommodityNationalTitle).HasMaxLength(50);
            entity.Property(e => e.Descriptions).HasMaxLength(1000);
            entity.Property(e => e.LevelCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MeasureTitle).HasMaxLength(100);
            entity.Property(e => e.SearchTerm).HasMaxLength(551);
            //entity.Property(e => e.SecondaryCode).HasMaxLength(50);
            entity.Property(e => e.Title).HasMaxLength(500);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CommoditeisView> entity);
    }
}
