// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Common;
using Eefa.Common.Data;
using Eefa.Sale.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Eefa.Sale.Data.Context.Configurations
{
    public partial class FixedPriceHistoryConfiguration : IEntityTypeConfiguration<FixedPriceHistory>
    {
        public void Configure(EntityTypeBuilder<FixedPriceHistory> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_FixedPrice");

            entity.ToTable("FixedPriceHistory", "Sale", tb => tb.HasComment("قیمت تمام شده"));

            entity.Property(e => e.CommodityId).HasComment("کد کالا");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");
            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");
            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");
            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");
            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");
            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");
            entity.Property(e => e.Price).HasComment("قیمت");
            entity.Property(e => e.StartDate).HasComment("تاریخ شروع");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FixedPriceHistory> entity);
    }
}
