// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Eefa.Accounting.Data.Entities.Configurations
{
    public partial class MoadianInvoiceDetailsConfiguration : IEntityTypeConfiguration<MoadianInvoiceDetail>
    {

        public void Configure(EntityTypeBuilder<MoadianInvoiceDetail> entity)
        {
            entity.ToTable("MoadianInvoiceDetails", "accounting");

            entity.Property(e => e.Adis).HasColumnType("money");

            entity.Property(e => e.Bros).HasColumnType("money");

            entity.Property(e => e.Bsrn).HasMaxLength(50);

            entity.Property(e => e.Cfee).HasColumnType("money");

            entity.Property(e => e.Consfee).HasColumnType("money");

            entity.Property(e => e.Cop).HasColumnType("money");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.Cut).HasMaxLength(50);

            entity.Property(e => e.Dis).HasColumnType("money");

            entity.Property(e => e.Exr).HasColumnType("money");

            entity.Property(e => e.Fee).HasColumnType("money");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.Mu)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Odam).HasColumnType("money");

            entity.Property(e => e.Odr).HasColumnType("money");

            entity.Property(e => e.Odt).HasMaxLength(50);

            entity.Property(e => e.Olam).HasColumnType("money");

            entity.Property(e => e.Olr).HasColumnType("money");

            entity.Property(e => e.Olt).HasMaxLength(50);

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.Prdis).HasColumnType("money");

            entity.Property(e => e.Spro).HasColumnType("money");

            entity.Property(e => e.Sscv).HasColumnType("money");

            entity.Property(e => e.Ssrv).HasColumnType("money");

            entity.Property(e => e.Sstid)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.Sstt)
                .IsRequired()
                .HasMaxLength(250);

            entity.Property(e => e.Tcpbs).HasColumnType("money");

            entity.Property(e => e.Tsstam).HasColumnType("money");

            entity.Property(e => e.Vam).HasColumnType("money");
            entity.Property(e => e.Am).HasColumnType("money");
            entity.Property(e => e.Vra).HasColumnType("money");
            entity.Property(e => e.Nw).HasColumnType("money");

            entity.Property(e => e.Vop).HasColumnType("money");

            entity.HasOne(d => d.InvoiceHeader)
                .WithMany(p => p.MoadianInvoiceDetails)
                .HasForeignKey(d => d.InvoiceHeaderId)
                .HasConstraintName("FK_MoadianInvoiceDetails_MoadianInvoiceHeaders");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MoadianInvoiceDetail> entity);
    }
}
