// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Eefa.Inventory.Domain;
#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class AccessToWarehouseConfiguration : IEntityTypeConfiguration<AccessToWarehouse>
    {
        public void Configure(EntityTypeBuilder<AccessToWarehouse> entity)
        {
            entity.ToTable("AccessToWarehouse", "inventory");

            entity.HasComment("دسترسی به اسناد و انبارها");

            entity.Property(e => e.Id).HasComment("شناسه");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AccessToWarehouse> entity);
    }
}
