// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Eefa.Inventory.Domain;
#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class AssetAttachmentsConfiguration : IEntityTypeConfiguration<AssetAttachments>
    {
        public void Configure(EntityTypeBuilder<AssetAttachments> entity)
        {
            entity.ToTable("AssetAttachments", "inventory");

            
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AssetAttachments> entity);
    }
}
