// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Invertory.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Inventory.Domain;


#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class DocumentPaymentConfiguration : IEntityTypeConfiguration<DocumentPayment>
    {
        public void Configure(EntityTypeBuilder<DocumentPayment> entity)
        {
            entity.ToTable("DocumentPayments", "common");

            entity.HasComment("اسناد پرداختی");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.Balance).HasComment("موازنه");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.DocumentHeadId).HasComment("کد سرفصل سند");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.IsPaied)
                .HasMaxLength(10)
                .IsFixedLength(true)
                .HasComment("پرداخت شده است");

            entity.Property(e => e.LadingNo).HasComment("شماره بارگیری");

            entity.Property(e => e.LiquidationPrice).HasComment("نرخ شناور");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.PaiedDate).HasComment("تاریخ پرداخت");

            entity.Property(e => e.PaymentDate).HasComment("تاریخ سررسید");

            //entity.HasOne(d => d.DocumentHead)
                //.WithMany(p => p.Payments)
                //.HasForeignKey(d => d.DocumentHeadId)
                //.OnDelete(DeleteBehavior.ClientSetNull)
                //.HasConstraintName("FK_DocumentPayment_DocumentHead");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocumentPayment> entity);
    }
}
