// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Invertory.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Inventory.Domain;



#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class WarehouseLayoutConfiguration : IEntityTypeConfiguration<WarehouseLayout>
    {
        public void Configure(EntityTypeBuilder<WarehouseLayout> entity)
        {
            entity.ToTable("WarehouseLayouts", "inventory");

            entity.HasComment("موقعیت های انبار");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.Capacity).HasComment("ظرفیت");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            entity.Property(e => e.EndIndex).HasComment("شماره پایان");

            entity.Property(e => e.EntryMode).HasComment("حالت ورود اطلاعات");

            entity.Property(e => e.IsChildSequncial).HasComment("زیر مجموعه بصورت سریال است");

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            entity.Property(e => e.LevelCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("کد سطح");

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            entity.Property(e => e.OrderIndex).HasComment("ترتیب نمایش");

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");

            entity.Property(e => e.ParentId).HasComment("کد والد");

            entity.Property(e => e.StartIndex).HasComment("شماره شروع");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("عنوان");

            entity.Property(e => e.UnitBaseTypeId).HasComment("نوع واحد کالا");

            entity.Property(e => e.WarehouseId).HasComment("کد انبار");

            entity.HasOne(d => d.Parent)
                .WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_WarehouseLayout_WarehouseLayout");

            entity.HasOne(d => d.UnitBaseType)
                .WithMany(p => p.WarehouseLayouts)
                .HasForeignKey(d => d.UnitBaseTypeId)
                .HasConstraintName("FK_WarehouseLayout_BaseValues");

            //entity.HasOne(d => d.Warehouse)
            //    .WithMany(p => p.WarehouseLayouts)
            //    .HasForeignKey(d => d.WarehouseId)
            //    .HasConstraintName("FK_WarehouseLayout_Warehouses");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WarehouseLayout> entity);
    }
}
