// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Invertory.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Inventory.Domain;



#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class WarehouseLayoutCategoriesConfiguration : IEntityTypeConfiguration<WarehouseLayoutCategories>
    {
        public void Configure(EntityTypeBuilder<WarehouseLayoutCategories> entity)
        {
            entity.ToTable("WarehouseLayoutCategories", "inventory");

            entity.HasComment("موقعیت های انبار");

            entity.Property(e => e.Id).HasComment("شناسه");

           

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");

            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");

            

            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");

            

            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");

            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");

            

            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WarehouseLayoutCategories> entity);
    }
}
