// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Invertory.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Inventory.Domain;


#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class WarehouseStocksConfiguration : IEntityTypeConfiguration<WarehouseStocks>
    {
        public void Configure(EntityTypeBuilder<WarehouseStocks> entity)
        {
            entity.ToTable("WarehouseStocks", "inventory");

            entity.Property(e => e.Id).HasComment("شناسه");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WarehouseStocks> entity);
    }
}
