// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Invertory.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Inventory.Domain;



#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class BomValueViewConfiguration : IEntityTypeConfiguration<BomValueView>
    {
        public void Configure(EntityTypeBuilder<BomValueView> entity)
        {
            entity.ToTable("BomValuesView", "inventory");

            entity.HasComment("مقادیر فرمول ساخت");

            entity.Property(e => e.Id).HasComment("شناسه");

            entity.Property(e => e.BomValueHeaderId).HasComment("کد سند فرمول ساخت");

            entity.Property(e => e.UsedCommodityId).HasComment("کد کالای مصرفی");

            entity.Property(e => e.Value).HasComment("مقدار");

           

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BomValueView> entity);
    }
}
