// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Invertory.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Inventory.Domain;


#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class CommodityPropertyWithThicknessViewConfiguration : IEntityTypeConfiguration<CommodityPropertyWithThicknessView>
    {
        public void Configure(EntityTypeBuilder<CommodityPropertyWithThicknessView> entity)
        {
            entity.ToTable("CommodityPropertyWithThicknessView", "inventory");

            OnConfigurePartial(entity);
        }

       

        partial void OnConfigurePartial(EntityTypeBuilder<CommodityPropertyWithThicknessView> entity);
    }
}
