// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Eefa.Inventory.Domain;
#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class EmployeesUnitsViewConfiguration : IEntityTypeConfiguration<EmployeesUnitsView>
    {
        public void Configure(EntityTypeBuilder<EmployeesUnitsView> entity)
        {
            entity.ToTable("EmployeesUnitsView", "inventory");

            entity.HasComment("کد واحد های سازمانی کارمندان");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmployeesUnitsView> entity);
    }
}
