// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Invertory.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Inventory.Domain;


#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class PersonsDebitedCommoditiesViewConfiguration : IEntityTypeConfiguration<PersonsDebitedCommoditiesView>
    {
        public void Configure(EntityTypeBuilder<PersonsDebitedCommoditiesView> entity)
        {
            entity.ToTable("PersonsDebitedCommoditiesView", "inventory");

           // OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonsDebitedCommoditiesView> entity);
    }
}
