// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Invertory.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Inventory.Domain;



#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class ReceiptGroupbyInvoiceViewConfiguration : IEntityTypeConfiguration<ReceiptGroupbyInvoiceView>
    {
        public void Configure(EntityTypeBuilder<ReceiptGroupbyInvoiceView> entity)
        {
            entity.ToTable("ReceiptGroupbyInvoiceView", "inventory");

            entity.HasComment("اسناد به تفکیک صورتحساب");

            entity.Property(e => e.Id).HasComment("اسناد به تفکیک صورتحساب");
            
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ReceiptGroupbyInvoiceView> entity);
    }
}
