// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Invertory.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Inventory.Domain;



#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class ReceiptWithCommodityViewConfiguration : IEntityTypeConfiguration<ReceiptWithCommodityView>
    {
        public void Configure(EntityTypeBuilder<ReceiptWithCommodityView> entity)
        {
            entity.ToTable("ReceiptWithCommodityView", "inventory");

            entity.HasComment("اسناد");

            entity.Property(e => e.Id).HasComment("شناسه");
            
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ReceiptWithCommodityView> entity);
    }
}
