// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Invertory.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using Eefa.Inventory.Domain;



#nullable disable

namespace Eefa.Invertory.Infrastructure.Context.Configurations
{
    public partial class View_Sina_FinancialOperationNumberConfiguration : IEntityTypeConfiguration<View_Sina_FinancialOperationNumber>
    {
        public void Configure(EntityTypeBuilder<View_Sina_FinancialOperationNumber> entity)
        {
            entity.ToTable("View_Sina_FinancialOperationNumber", "dbo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<View_Sina_FinancialOperationNumber> entity);
    }
}
