// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Eefa.Common.Data;
using System;
using System.Collections.Generic;

namespace Eefa.Bursary.Domain.Entities.Payables
{
    public partial class Payables_DocumentsPayOrders : BaseEntity
    {
        public int DocumentId { get; set; }
        public int PayOrderId { get; set; }
        public virtual Payables_Documents Document { get; set; }

    }
}