// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Eefa.Bursary.Domain.Entities;
using Eefa.Bursary.Domain.Entities.Definitions;
using Eefa.Common.Data;
using System;
using System.Collections.Generic;

namespace Eefa.Bursary.Domain.Entities
{
    public partial class Payables_ChequeBooks : BaseEntity
    {
        public Payables_ChequeBooks()
        {
            Payables_ChequeBooksSheets = new HashSet<Payables_ChequeBooksSheets>();
        }

        public int BankAccountId { get; set; }
        public DateTime GetDate { get; set; }
        public string Serial { get; set; }
        public int SheetsCount { get; set; }
        public long StartNumber { get; set; }
        public string? Descp { get; set; }

        public virtual BankAccounts BankAccount { get; set; }
        public virtual ICollection<Payables_ChequeBooksSheets> Payables_ChequeBooksSheets { get; set; }
    }
}