// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Eefa.Common;
using Eefa.Common.Data;
using Eefa.Warehouse.Infrastructure.Data.Context;
using Eefa.Warehouse.Infrastructure.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Eefa.Warehouse.Infrastructure.Data.Context.Configurations
{
    public partial class WarehouseHistoryConfiguration : IEntityTypeConfiguration<WarehouseHistory>
    {
        public void Configure(EntityTypeBuilder<WarehouseHistory> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_WarehouseHistory");

            entity.ToTable("WarehouseHistories", "inventory", tb => tb.HasComment("تاریخچه انبار ها"));

            entity.HasIndex(e => e.Commodityld, "IX_WarehouseHistories_CommodityId");

            entity.HasIndex(e => e.IsDeleted, "IX_WarehouseHistories_IsDeleted");

            entity.HasIndex(e => e.WarehousesId, "IX_WarehouseHistories_WarehouseId");

            entity.HasIndex(e => e.DocumentItemId, "IX_WarehouseHistories_documentItemsId");

            entity.Property(e => e.Id).HasComment("شناسه");
            entity.Property(e => e.Commodityld).HasComment("کد کالا");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان ایجاد");
            entity.Property(e => e.CreatedById).HasComment("ایجاد کننده");
            entity.Property(e => e.DocumentItemId).HasComment("شماره آیتم در سند");
            entity.Property(e => e.IsDeleted).HasComment("آیا حذف شده است؟");
            entity.Property(e => e.Mode).HasComment("نوع عملیات");
            entity.Property(e => e.ModifiedAt)
                .HasDefaultValueSql("(getdate())")
                .HasComment("تاریخ و زمان اصلاح");
            entity.Property(e => e.ModifiedById).HasComment("اصلاح کننده");
            entity.Property(e => e.OwnerRoleId).HasComment("نقش صاحب سند");
            entity.Property(e => e.Quantity).HasComment("تعداد");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WarehouseHistory> entity);
    }
}
